DROP DATABASE IF EXISTS `19wh1a1284`;
CREATE SCHEMA 19wh1a1284;
USE 19wh1a1284;
CREATE TABLE bus(bus_no INT , bus_type VARCHAR(20) , source VARCHAR(30) , destination VARCHAR(30) );
INSERT INTO bus VALUES(4590 , 'PRIVATE' , 'Mahabubabad' , 'Warangal');
INSERT INTO bus VALUES(5409 , 'PUBLIC' , 'Adilabad' , 'Hyderabad');
INSERT INTO bus VALUES(4095 , 'PUBLIC' , 'Khammam' , 'Mahaboobnagar');
INSERT INTO bus VALUES(9054 , 'PRIVATE' , 'Karimnagar' , 'Bhadrachalam');
SELECT * FROM bus ;
DELETE FROM bus b WHERE b.bus_no = 5409;
SELECT * FROM bus ;
CREATE TABLE Passanger(name VARCHAR(20) ,age INT ,  source VARCHAR(30) , destination VARCHAR(30) );
INSERT INTO Passanger VALUES('Pooja' ,19, 'Hyderabad' , 'khammam' );
INSERT INTO Passanger VALUES('Bharani' ,55, 'Hyderabad' , 'Bhadrachalam' );
INSERT INTO Passanger VALUES('Vaishnavi' ,30, 'Hyderabad' , 'Warangal' );
INSERT INTO Passanger VALUES('Lalitha' ,36, 'Hyderabad' , 'Guntur' );
SELECT * FROM Passanger ;
DELETE FROM Passanger P WHERE P.name = 'pooja';
SELECT * FROM Passanger ;
CREATE TABLE Ticket(ticket_type VARCHAR(20) ,ticket_no INT , amount INT , source VARCHAR(30) , destination VARCHAR(30) );
INSERT INTO Ticket VALUES('FULL' , 405 , 200 , 'Hyderabad' , 'khammam' );
INSERT INTO Ticket VALUES('HALF' , 406 , 50, 'Warangal' , 'hyderabad' );
INSERT INTO Ticket VALUES('FULL' , 407 , 100, 'Warangal' , 'karimnagar' );
INSERT INTO Ticket VALUES('HALF' , 408 , 100, 'Hyderabad' , 'siddipet' );
SELECT * FROM Ticket ;
DELETE FROM Ticket t WHERE ticket_no = 405;
SELECT * FROM Ticket ;
